# Generated by Django 4.1.2 on 2022-11-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificates_name', models.CharField(max_length=100)),
                ('Certificates_image', models.ImageField(default='', upload_to='Portfolio/images/Certificates')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Works_name', models.CharField(max_length=100)),
                ('Works_image', models.ImageField(default='', upload_to='Portfolio/images/Works')),
                ('Works_visit_url', models.URLField(blank=True)),
                ('Works_source_url', models.URLField(blank=True)),
            ],
        ),
    ]
